---
# Here we basically moving username and password to yaml_demo

- name: Take global command
  hosts: S1,S2
  connection: local
  gather_facts: no
  vars_files:
    - /home/patryk/Ansible-GNS3/static_routes/yaml_demo.yaml
#./yaml_demo.yaml - if it's in the same location


  tasks:
  - name: INPUT SHOW COMMAND TO DEVICES
    eos_config:
      src: add_static_route.j2  
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ USERNAME }}"
        password: "{{ DEVICE_PASSWORD }}"
        use_ssl: no
        authorize: yes
        transport: cli



      #lines:
      #  - "{{ OPTUNNEL01A }}"
      #  - "{{ OPTUNNEL01B }}"
  #  register: print_output

#  - name: OUTPUT SHOW COMMAND to SCREEN
  #  debug:
  #    msg: "{{ print_output.stdout_lines }}"
