---
# Here we basically moving username and password to yaml_demo

- name: Take show command input
  hosts: all
  connection: local
  gather_facts: false
  vars_files:
    - /home/patryk/Ansible-GNS3/show_command2/yaml_demo.yaml
#./yaml_demo.yaml - if it's in the same location

  vars_prompt:
   # - name: USERNAME
   #   aprompt: "Please put your username"
   #   private: no
   # - name: DEVICE_PASSWORD
   #   prompt: "Please put your password"
   #   private: yes
    - name: SHOW_COMMAND
      prompt: "Please enter the full show command you want to run"
      private: no






  tasks:
  - name: INPUT SHOW COMMAND TO DEVICES
    eos_command:
      commands: "{{ SHOW_COMMAND }}"
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ USERNAME }}"
        password: "{{ DEVICE_PASSWORD }}"
        use_ssl: no
        authorize: yes
        transport: cli
    register: print_output

  - name: OUTPUT SHOW COMMAND to SCREEN
    debug:
      msg: "{{ print_output.stdout_lines }}"

  - name: OUTPUT SHOW COMMAND to FILE
    copy: content="{{ print_output.stdout[0] }}" dest="./output/{{ inventory_hostname }}.txt"
